language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1


before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - vendor/bin/codecept build

script: vendor/bin/codecept run
